### ISSUE TITLE
avfan1.yaml display

### ISSUE THREAD

**Issue by fabianmuehlberger** [ESP32andmore/ECB#2]
While testing the avfan1.yaml i noticed the following compile errors.

> Failed config
> 
> font: [source fancontrol.yaml:301]
>   - 
>     Could not find file 'fonts/comic-sans-ms/ComicSansMS3.ttf'. Please make sure it exists (full path: /root/fonts/comic-sans-ms/ComicSansMS3.ttf).

There is a display component for a ssd1306 in the config file, not sure why it is included in the sketch since the board has no display and there is no display mentioned in the setup and config guide. 

removing "my_font" from the display allows compiling, but IMHO this should not be included in the basic config example.

**Comment by ESP32andmore** [comment]
Yes, you are correct it probably should not be in there and I'll upload that to Github.  It is in our functional testing and with an update made it way into the example code.  Just delete the reference to the device and myfontGet Outlook for AndroidFrom: Fabian Muehlberger ***@***.***>Sent: Thursday, September 19, 2024 5:03:25 AMTo: ESP32andmore/ECB ***@***.***>Cc: Subscribed ***@***.***>Subject: [ESP32andmore/ECB] avfan1.yaml display (Issue #2)
While testing the avfan1.yaml i noticed the following compile errors.

Failed config
font: [source fancontrol.yaml:301]
Could not find file 'fonts/comic-sans-ms/ComicSansMS3.ttf'. Please make sure it exists (full path: /root/fonts/comic-sans-ms/ComicSansMS3.ttf).


There is a display component for a ssd1306 in the config file, not sure why it is included in the sketch since the board has no display and there is no display mentioned in the setup and config guide.
removing "my_font" from the display allows compiling, but IMHO this should not be included in the basic config example.
